FROM ruby:2.4.0-slim
MAINTAINER Team Charlie <csd@abdn.ac.uk>

ARG http_proxy
ARG https_proxy
ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

RUN echo 'Acquire::http::Proxy "$http_proxy";' > /etc/apt/apt.conf

RUN apt-get update -qq && apt-get -y install build-essential libpq-dev nodejs curl imagemagick

RUN mkdir -p /lacr-demo
WORKDIR /lacr-demo

ADD lacr-demo/Gemfile /lacr-demo/Gemfile
ADD lacr-demo/Gemfile.lock /lacr-demo/Gemfile.lock

RUN bundle install

ADD lacr-demo /lacr-demo

RUN echo '' > /etc/apt/apt.conf

ENV http_proxy=''
ENV http_proxy=''
