#!/bin/bash
# Description: Shell-script to start rails server

read -r -p "Would you like to rebuild the docker image? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
	read -r -p "Would you like to NOT build the rails container through University proxy server? [y/N] " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
	then
		docker-compose build
	else
	  	docker-compose build -f docker-compose-proxy.yml
	fi
fi

read -r -p "Would you like to run \"rails db:drop db:create db:migrate\"? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
  docker-compose run web bash -c "rails db:drop && rails db:create && rails db:migrate"
fi

echo ''
echo 'Starting containers ....'
docker-compose up
